version: "3.8"
services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: "mongodb://db:27017/backend1"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - data-volume:/data/db

volumes:
  data-volume: